### ISSUE TITLE
Possibility of filling data in from a .txt file (More of an ask than a problem)

### ISSUE THREAD

**Issue by jimbo4273** [supercarotte/PSSE#4]
I was wondering if it would be possible (or easy) to make a function where you can input stage savedata from a .txt file. I currently have been putting all of my stage scores in one sheet, separated by expert and main, and have been wanting to port my game over from mobile. The Obtained Pokemon part was simple (yet tedious), but I feel that inputting stage data for ~375 stages will take a long time.

**Comment by supercarotte** [comment]
I find that idea pretty cool since I always wondered how I could implement batch score-editing (aside from setting the minimal score required for a particular rank).

It's not really a super important feature, so I can't say I will do it but that's definitely something I could see  in PSSE if I get in the mood.
